export const menu = [
  {
    id: "ribs-brisket-and-burnt-ends",
    img: "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/79619/joes-kc-ribs-brisket-and-burnt-ends.6710e994980e485e6441b794717ad6fb.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    name: "Joe's KC BBQ",
    dsc: "Joe's KC Ribs, Brisket & Burnt Ends",
    price: 110.99,
    rate: 4,
    country: "Kansas City, KS",
    category: "barbeque",
  },
  {
    id: "texas-monthlys-1-bbq-brisket",
    img: "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/131249/texas-monthlys-1-bbq-brisket.1006a061be7acae03992e420fbca995a.png?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    name: "Snow's BBQ",
    dsc: "Texas Monthly's #1 BBQ Brisket",
    price: 199,
    rate: 4,
    country: "Lexington, TX",
    category: "barbeque",
  },
  {
    id: "005-kings-carolina-oink-sampler",
    img: "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/66752/carolina-bbq-oink-sampler.1340b5a10cedc238cb2280306dd1d5a5.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    name: "Kings BBQ",
    dsc: "Carolina BBQ Oink Sampler",
    price: 89,
    rate: 4,
    country: "Kinston, NC",
    category: "barbeque",
  },
  {
    id: "whole-brisket-texas-bbq-sauce",
    img: "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/110384/whole-brisket-texas-barbecue-bbq-sauce.e07ee4818b20ed43d217bf67fedd41ce.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    name: "Franklin Barbecue",
    dsc: "Whole Brisket + Texas Barbecue BBQ Sauce",
    price: 249,
    rate: 4,
    country: "Austin, TX",
    category: "barbeque",
  },
  {
    id: "mini-trinity-bbq-combo-brisket-ribs-and-links",
    img: "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/90406/mini-trinity-bbq-combo-brisket-ribs-and-links.245582f593bf64b23b57dfca2be18cfd.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    name: "Bludso's BBQ",
    dsc: "Mini Trinity BBQ Combo - Brisket, Ribs & Links",
    price: 139,
    rate: 4,
    country: "Los Angeles, CA",
    category: "barbeque",
  },
  {
    id: "006-kings-meat-lovers-special",
    img: "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/66734/bbq-meat-lovers-special-for-10.36ca670fda4bfa783c2ea9165e068d26.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    name: "Kings BBQ",
    dsc: "BBQ Meat Lovers Special for 10",
    price: 139,
    rate: 5,
    country: "Kinston, NC",
    category: "barbeque",
  },
  {
    id: "17796-mighty-quinns-bbq-sampler-pack",
    img: "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/134182/mighty-quinns-bbq-sampler-pack.1bfe4a0665edc565756f5241bf25840e.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    name: "Mighty Quinn's BBQ",
    dsc: "Mighty Quinn's BBQ Sampler Pack",
    price: 169,
    rate: 5,
    country: "New York, NY",
    category: "barbeque",
  },
  {
    id: "choose-your-own-world-championship-bbq-4-pack",
    img: "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/133378/choose-your-own-world-championship-bbq-4-pack.d5216e2b1c2a92f481fc9d1c7a15e8df.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    name: "Big Bob Gibson Bar-B-Q",
    dsc: "Choose Your Own World Championship BBQ - 4 Pack",
    price: 109.95,
    rate: 4,
    country: "Decatur, AL",
    category: "barbeque",
  },
  {
    id: "hog-heaven",
    img: "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/79576/hog-heaven-pulled-pork-sausage-links.5012c36f6f049c131b04345c5326e4d3.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    name: "Joe's KC BBQ",
    dsc: "Hog Heaven - Pulled Pork + Sausage Links",
    price: 69.99,
    rate: 4,
    country: "Kansas City, KS",
    category: "barbeque",
  },
  {
    id: "bbq-rib-tips-serves-10-15",
    img: "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/90450/bbq-rib-tips-serves-10-15.c3f35f44d3b1650273c3cdd42494fb66.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    name: "Bludso's BBQ",
    dsc: "BBQ Rib Tips - Serves 10-15",
    price: 109,
    rate: 5,
    country: "Los Angeles, CA",
    category: "barbeque",
  },
  {
    id: "shake-shack-shackburger-8-pack",
    img: "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/134862/shake-shack-shackburger-8-pack.973a5e26836ea86d7e86a327becea2b0.png?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    name: "Shake Shack",
    dsc: "Shake Shack ShackBurger® – 8 Pack",
    price: 49,
    rate: 5,
    country: "New York, NY",
    category: "burgers",
  },
  {
    id: "gotts-cheeseburger-kit-for-4",
    img: "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/132933/gotts-complete-cheeseburger-kit-for-4.7bdc74104b193427b3fe6eae39e05b5e.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    name: "Gott's Roadside",
    dsc: "Gott's Complete Cheeseburger Kit for 4",
    price: 99,
    rate: 5,
    country: "St. Helena, CA",
    category: "burgers",
  },
  {
    id: "le-big-matt-kit-for-6",
    img: "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/131436/le-big-matt-kit-for-6.1ddae6e382bb3218eeb0fd5247de115a.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    name: "Emmy Squared",
    dsc: "Le Big Matt Burger Kit for 6",
    price: 99,
    rate: 5,
    country: "Brooklyn, NY",
    category: "burgers",
  },

  {
    id: "21-usda-prime-burgers-pack-of-18-8oz-each",
    img: "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/133009/usda-prime-burgers-pack-of-18-8oz-each.274c67f15aa1c0b210dbf51801706670.png?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    name: "Peter Luger Steak House",
    dsc: "USDA Prime Burgers - Pack of 18 (8oz each)",
    price: 175.95,
    rate: 4,
    country: "Brooklyn, NY",
    category: "burgers",
  },
  {
    id: "double-stack-burger-kit-for-4",
    img: "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/122768/handf-double-stack-burger-kit-for-4.4ee9f54b1d6087e9996335f07c13e5cd.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    name: "Holeman & Finch",
    dsc: "Double Stack Burger Kit for 4",
    price: 79,
    rate: 4,
    country: "Atlanta, GA",
    category: "burgers",
  },
  {
    id: "goldbelly-burger-bash-pack",
    img: "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/66179/the-burger-bash-package.bd9d12d031865940bbe5faf15f1a62f8.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    name: "Pat LaFrieda Meats",
    dsc: 'Goldbelly "Burger Bash" Pack',
    price: 109,
    rate: 5,
    country: "North Bergen, NJ",
    category: "burgers",
  },
  {
    id: "burger-au-poivre-kit-4-pack",
    img: "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/103477/burger-au-poivre-kit-4-pack.3ca0e39b02db753304cd185638dad518.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    name: "Raoul's",
    dsc: "Burger Au Poivre Kit - 4 Pack",
    price: 99,
    rate: 4,
    country: "New York, NY",
    category: "burgers",
  },
  {
    id: "juicy-lucy-burger-kit-5-pack",
    img: "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/132203/juicy-lucy-burger-kit-5-pack.2902a0c8549449529e87f902f425f9ae.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    name: "Whitmans",
    dsc: "Juicy Lucy Burger Kit - 5 Pack",
    price: 79,
    rate: 5,
    country: "New York, NY",
    category: "burgers",
  },
  {
    id: "best-damn-cheeseburger-kit",
    img: "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/134005/best-damn-cheeseburger-kit-8-pack.0c2ca295cc1b754d2867651184a07140.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    name: "4505 Burgers & BBQ",
    dsc: "Best Damn Cheeseburger Kit - 8 Pack",
    price: 89,
    rate: 5,
    country: "San Francisco, CA",
    category: "burgers",
  },
  {
    id: "le-pig-mac-kit-for-4",
    img: "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/106701/le-pig-mac-kit-for-4.d9b274673ffc1a1a2035c9573291cae2.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    name: "Cochon Butcher",
    dsc: "Le Pig Mac Kit for 4",
    price: 109,
    rate: 4,
    country: "New Orleans, LA",
    category: "burgers",
  },
  {
    id: "15259-german-chocolate-killer-brownie-tin-pack",
    img: "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/132029/german-chocolate-killer-brownie-tin-pack.5ebc34160f28767a9d94c4da2e04c4b9.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    name: "Killer Brownie®",
    dsc: "German Chocolate Killer Brownie®",
    price: 39.99,
    rate: 4,
    country: "Dayton, OH",
    category: "desserts",
  },
  {
    id: "jacques-world-famous-chocolate-chip-cookies",
    img: "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/81172/jacques-world-famous-chocolate-chip-cookies-6-pack.2217a14c443602493bba88aa9335319a.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    name: "Jacques Torres Chocolate",
    dsc: "Jacques’ World Famous Chocolate Chip Cookies - 6 Pack",
    price: 39.95,
    rate: 4,
    country: "New York, NY",
    category: "desserts",
  },
  {
    id: "luigis-original-cannoli-pie",
    img: "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/132206/original-cannoli-pie.4cb5b9ba82f57b69b90765fd9f07aa1a.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    name: "The Cannoli Pie Company",
    dsc: "Original Cannoli Pie",
    price: 69,
    rate: 4,
    country: "Bridgeport, CT",
    category: "desserts",
  },
  {
    id: "sea-salted-caramel-swirl-cheesecake",
    img: "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/134006/sea-salted-caramel-swirl-cheesecake.e2825335433fb7a272a5d77649a6849e.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    name: "Cotton Blues Cheesecake Company",
    dsc: "Sea-Salted Caramel Swirl Cheesecake",
    price: 65,
    rate: 4,
    country: "Hattiesburg, MS",
    category: "desserts",
  },
  {
    id: "smores-variety-pack",
    img: "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/78037/smores-variety-pack.86cf47d40c0c3508ce14d2659b3f99d4.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    name: "Gotta Have S'more",
    dsc: "S'mores - Variety Pack",
    price: 49,
    rate: 5,
    country: "Los Angeles, CA",
    category: "desserts",
  },
  {
    id: "best-seller-cupcake-dozen",
    img: "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/94478/best-seller-cupcake-dozen.f93b21993f6a2da11c975d45b9b0d08f.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    name: "Crave Cupcakes",
    dsc: "Best Seller Cupcake Dozen",
    price: 89,
    rate: 4,
    country: "Houston, TX",
    category: "desserts",
  },
  {
    id: "choose-your-own-ice-cream-donuts-6-pack1",
    img: "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/132716/choose-your-own-ice-cream-donuts-6-pack.24d0b44765a7c54237fcd7ea9d9d8093.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    name: "Elegant Desserts",
    dsc: "Choose Your Own Ice Cream Donuts - 6 Pack",
    price: 69,
    rate: 5,
    country: "Brooklyn, NY",
    category: "desserts",
  },
  {
    id: "17481-jewish-dessert-3-pack",
    img: "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/72507/jewish-classics-dessert-pack.7d4b76630f2fe75dcb7bbcf2501b7390.png?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    name: "Ess-a-Bagel",
    dsc: "Jewish Classics Dessert Pack",
    price: 89.95,
    rate: 5,
    country: "New York, NY",
    category: "desserts",
  },
  {
    id: "dessert-bar-care-package",
    img: "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/131609/dessert-bar-care-package.324aa28fe98c9dc67b75aac43376902e.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    name: "Bread and Roses Bakery",
    dsc: "Dessert Bar Care Package",
    price: 65,
    rate: 4,
    country: "Wells, ME",
    category: "desserts",
  },
  {
    id: "donut-cookies-12-pack",
    img: "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/97746/donut-cookies-12-pack.46f42c61c4a79fd2051a99b2f23e890e.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    name: "Stan's Donuts",
    dsc: "Donut Cookies - 12 Pack",
    price: 49,
    rate: 5,
    country: "Chicago, IL",
    category: "desserts",
  },
  {
    id: "hong-kong-boba-tea-kit-for-6",
    img: "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/108725/hong-kong-boba-tea-kit-for-6.63841de36d8e5edfafa13023fc303285.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    name: "New Territories",
    dsc: "Hong Kong Boba Tea Kit for 6",
    price: 59,
    rate: 4,
    country: "New York, NY",
    category: "drinks",
  },
  {
    id: "guys-caliente-margaritas-for-12",
    img: "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/126836/guys-caliente-margaritas-for-12.ca8c6bc06b8f1039549385ffcebc749d.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    name: "Guy Fieri",
    dsc: "Guy's Caliente Margaritas for 12",
    price: 69,
    rate: 5,
    country: "Flavortown, USA",
    category: "drinks",
  },
  {
    id: "woodford-reserve-mint-julep-syrup",
    img: "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/134036/woodford-reserve-mint-julep-syrup.ef523ac7cbae5f4aba6b058207f490d2.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    name: "Woodford Reserve",
    dsc: "Woodford Reserve Mint Julep Syrup",
    price: 39,
    rate: 4,
    country: "Louisville, KY",
    category: "drinks",
  },
  {
    id: "new-orleans-hurricane-mix",
    img: "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/84522/new-orleans-hurricane-mix.4613584fc65cb0787024dd24d2a8f4b3.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    name: "Franco's Hurricane Mix",
    dsc: "New Orleans Hurricane Mix",
    price: 39,
    rate: 5,
    country: "Natchitoches, LA",
    category: "drinks",
  },
  {
    id: "chickpea-chiller-kit-for-6",
    img: "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/106484/chickpea-chiller-kit-for-6.4310765c71ba524b5462ea9330d32446.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    name: "The Hummus & Pita Co.",
    dsc: "Chickpea Chiller Kit for 6",
    price: 89,
    rate: 5,
    country: "New York, NY",
    category: "drinks",
  },
  {
    id: "mr-grumpy-milkshake-kit-for-8",
    img: "https://goldbelly.imgix.net/uploads/product_image/image/75112/mr-grumpy-milkshake-kit-for-8.174f846e3252d7c668d034776db22cd6.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    name: "New Territories",
    dsc: "Mr. Grumpy Milkshake Kit for 8",
    price: 109,
    rate: 5,
    country: "New York, NY",
    category: "drinks",
  },
  {
    id: "POB1-pat-obriens-new-orleans-drink-mixes",
    img: "https://goldbelly.imgix.net/uploads/product_image/image/27512/pat-obriens-new-orleans-drink-mixes.977ee6c9de74923c63a180468ff94a86.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    name: "Pat O'Brien's Hurricanes",
    dsc: "Pat O'Brien's New Orleans Drink Mixes",
    price: 25,
    rate: 5,
    country: "New Orleans, LA",
    category: "drinks",
  },
  {
    id: "002-cafe-du-monde-coffee-and-beignets",
    img: "https://goldbelly.imgix.net/uploads/product_image/image/55362/cafe-du-monde-coffee-and-beignet-mix.c9db4d8ac11248a827f9e5dbf056fe7f.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    name: "Cafe du Monde Beignets",
    dsc: "Cafe du Monde Coffee & Beignet Mix",
    price: 29,
    rate: 5,
    country: "New Orleans, LA",
    category: "drinks",
  },
  {
    id: "virtual-cocktail-party-kit",
    img: "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/102046/virtual-cocktail-party-kit.32af5b8dcdc21513673ff28a32f79edc.JPG?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    name: "Tipsy Scoop Boozy Ice Cream",
    dsc: "Boozy Ice Cream Cocktail Party Kit",
    price: 109,
    rate: 5,
    country: "New York, NY",
    category: "drinks",
  },
  {
    id: "choose-your-own-new-haven-style-pizza-6-pack",
    img: "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/131840/choose-your-own-new-haven-style-pizza-6-pack.ab82828afc6172cdd4017556c15e36dd.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    name: "Zuppardi's Apizza",
    dsc: "New Haven-Style Pizza - 6 Pack (Choose Your Own)",
    price: 79,
    rate: 4,
    country: "West Haven, CT",
    category: "pizzas",
  },
  {
    id: "6-lou-malnatis-deep-dish-pizzas",
    img: "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/106829/6-lou-malnatis-deep-dish-pizzas.f59993181da5d295668c8a6fb856055e.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    name: "Lou Malnati's Pizza",
    dsc: "6 Lou Malnati's Deep Dish Pizzas",
    price: 116.99,
    rate: 4,
    country: "Chicago, IL",
    category: "pizzas",
  },
  {
    id: "wood-fired-pizzas-best-seller-4-pack",
    img: "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/106027/wood-fired-pizzas-best-seller-4-pack.1653bb05922ba153ac178f8365d27f6d.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    name: "Pizzeria Bianco",
    dsc: "Wood Fired Pizzas Best Seller - 4 Pack",
    price: 129,
    rate: 5,
    country: "Phoenix, AZ",
    category: "pizzas",
  },
  {
    id: "brooklyn-pizza-choose-your-own-5-pack",
    img: "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/104938/brooklyn-pizza-choose-your-own-5-pack.edc4f476a75207d0af840ce6f225f2b3.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    name: "Paesan’s Pizza",
    dsc: "Brooklyn Pizza - Choose Your Own 5 Pack",
    price: 69,
    rate: 4,
    country: "Albany, NY",
    category: "pizzas",
  },
  {
    id: "tonys-custom-pizza-3-pack",
    img: "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/131555/choose-your-own-pizza-3-pack.fcf7a43e38593007ef2857fe16d6dd26.png?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    name: "Tony's Pizza Napoletana",
    dsc: "Choose Your Own Pizza - 3 Pack",
    price: 99,
    rate: 5,
    country: "San Francisco, CA",
    category: "pizzas",
  },
  {
    id: "choose-your-own-3-pizzas",
    img: "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/133289/choose-your-own-3-pizzas.a6de480878c0b3b9f4d240bacbb665e7.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    name: "Heggies Pizza",
    dsc: "Choose Your Own - 3 Pizzas",
    price: 79,
    rate: 4,
    country: "Milaca, MN",
    category: "pizzas",
  },
  {
    id: "15952-create-your-own-pizza-3-pack",
    img: "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/133262/choose-your-own-pizza-3-pack.7ee3cc9bbc48b97a0f66e073d4071982.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    name: "Detroit Style Pizza Co",
    dsc: "Detroit Pizza - Choose Your Own Pizza 3 Pack",
    price: 85,
    rate: 4,
    country: "Detroit, MI",
    category: "pizzas",
  },
  {
    id: "neapolitan-pizza-choose-your-own-3-Pack",
    img: "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/119426/neapolitan-pizza-choose-your-own-3-pack.dada483ad51fe8e1f8b06c68a8f1356f.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    name: "Motorino Pizzeria",
    dsc: "Neapolitan Pizza - Choose Your Own 3 Pack",
    price: 99,
    rate: 4,
    country: "New York, NY",
    category: "pizzas",
  },
  {
    id: "original-cheese-new-york-pizza-2-pack",
    img: "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/104910/cheese-neapolitan-pizza-2-pack.856b6b14d276981a4654e1bb348cb328.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    name: "Joe & Pats Pizzeria",
    dsc: "Original Cheese New York Pizza - 2 Pack",
    price: 79,
    rate: 4,
    country: "Staten Island, NY",
    category: "pizzas",
  },

  {
    id: "choose-your-own-ice-cream-12-pints",
    img: "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/96047/ice-cream-choose-your-own-12-pints.e57770eaab1a0b7837095eda979e9a2b.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    name: "Graeter's Ice Cream",
    dsc: "Ice Cream - Choose Your Own 12 Pints",
    price: 119.95,
    rate: 4,
    country: "Cincinnati, OH",
    category: "ice cream",
  },
  {
    id: "choose-your-own-ice-cream-donuts-6-pack",
    img: "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/132716/choose-your-own-ice-cream-donuts-6-pack.24d0b44765a7c54237fcd7ea9d9d8093.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    name: "Elegant Desserts",
    dsc: "Choose Your Own Ice Cream Donuts - 6 Pack",
    price: 69,
    rate: 5,
    country: "Brooklyn, NY",
    category: "ice cream",
  },
  {
    id: "mochi-ice-cream-choose-your-own-12-pack",
    img: "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/122636/mochi-ice-cream-choose-your-own-12-pack.f6eb9b1a2020a9ff88c8bb069a910b22.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    name: "Mochii",
    dsc: "Mochi Ice Cream - Choose Your Own 12 Pack",
    price: 75,
    rate: 5,
    country: "New York, NY",
    category: "ice cream",
  },
  {
    id: "giant-ice-cream-sandwich-kit-choose-your-own-6-pack",
    img: "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/132386/build-your-own-ice-cream-sandwich-kit-6-pack.c81bd69ed1a452decb5bc599358dc644.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    name: "The Baked Bear",
    dsc: "Build Your Own Ice Cream Sandwich Kit - 6 Pack",
    price: 84,
    rate: 5,
    country: "San Diego, CA",
    category: "ice cream",
  },
  {
    id: "cookie-monster-ice-cream-sandwich-8-pack",
    img: "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/131739/cookie-monster-ice-cream-sandwich-8-pack.9ad71ce3dd6f39fcbddc35af60a3b866.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    name: "Nightingale Ice Cream Sandwiches",
    dsc: "Cookie Monster Ice Cream Sandwich - 8 Pack",
    price: 75,
    rate: 4,
    country: "Richmond, VA",
    category: "ice cream",
  },
  {
    id: "giant-ice-cream-sandwich-kit-choose-your-own-9-pack",
    img: "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/103337/build-your-own-ice-cream-sandwich-kit-9-pack.e972c9c8819bfc245d671eaf98107247.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    name: "The Baked Bear",
    dsc: "Build Your Own Ice Cream Sandwich Kit - 9 Pack",
    price: 99,
    rate: 5,
    country: "San Diego, CA",
    category: "ice cream",
  },
  {
    id: "flavors-of-kentucky-ice-cream-collection-6-pints",
    img: "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/95847/taste-of-kentucky-ice-cream-collection-6-pints.8e530e9a1dd44524fb25ab59976024da.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    name: "Crank & Boom Craft Ice Cream",
    dsc: "Flavors of Kentucky Ice Cream Collection - 6 Pints",
    price: 99,
    rate: 4,
    country: "Lexington, KY",
    category: "ice cream",
  },
  {
    id: "artisanal-bread-choose-your-own-3-pack",
    img: "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/132332/artisanal-bread-choose-your-own-3-pack.c64d8dc0584457116b91a24f43cd861c.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    name: "Orwashers Bakery",
    dsc: "Artisanal Bread - Choose Your Own 3 Pack",
    price: 45,
    rate: 5,
    country: "New York, NY",
    category: "bread",
  },
  {
    id: "tartine-bread-loaves-choose-your-own-2-pack",
    img: "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/133401/tartine-bread-loaves-choose-your-own-2-pack.aa052bf998aa1b627e1fa71a482311a7.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    name: "Tartine Bakery",
    dsc: "Tartine Bread Loaves - Choose Your Own 2 Pack",
    price: 39,
    rate: 4,
    country: "San Francisco, CA",
    category: "bread",
  },
  {
    id: "23572-artichoke-bread-sampler-4-pack",
    img: "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/89514/artichoke-bread-sampler-4-pack.2243d37a2b976f88cdfe026026e82e1f.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    name: "Arcangeli Grocery",
    dsc: "Artichoke Bread Sampler - 4 Pack",
    price: 59,
    rate: 4,
    country: "Pescadero, CA",
    category: "bread",
  },
  {
    id: "bavarian-soft-pretzel-twists-10-pack",
    img: "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/133455/bavarian-soft-pretzel-twists-10-pack.0f8c34ca7341a525bd581924bd9f030f.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    name: "Milwaukee Pretzel Company",
    dsc: "Bavarian Soft Pretzel Twists - 10 Pack",
    price: 39,
    rate: 4,
    country: "Milwaukee, WI",
    category: "bread",
  },
  {
    id: "classic-clam-chowder-and-bread-bowls-4-pack",
    img: "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/98280/classic-clam-chowder-and-bread-bowls-4-pack.ce07ef6072a276e55bb2924f56d74ebb.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    name: "Boudin Bakery",
    dsc: "Classic Clam Chowder and Bread Bowls Kit - 4 Pack",
    price: 49,
    rate: 4,
    country: "San Francisco, CA",
    category: "bread",
  },
  {
    id: "original-garlic-cream-cheese-bread-2-pack",
    img: "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/105205/original-garlic-cream-cheese-bread-2-pack.7cb55509860ca0311b97222aae4eb0b2.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    name: "Calic Bread",
    dsc: "Original Garlic Cream Cheese Bread - 2 Pack",
    price: 79,
    rate: 5,
    country: "Los Angeles, CA",
    category: "bread",
  },
];
